/* ANOVA5.SAS : TWO-WAY LAYOUT */
OPTIONS PS=55 NODATE;
TITLE1 'ANOVA : TWO-WAY LAYOUT WITH MEANS COMPARISONS';
DATA ;
  INPUT GROUP $ DRUG $ SCORE @@;
  DATALINES;
 N P 50 N R 67
 N P 45 N R 60
 N P 55 N R 58
 N P 52 N R 65
 H P 70 H R 51
 H P 72 H R 57
 H P 68 H R 48
 H P 75 H R 55
;
RUN;
PROC ANOVA;
  CLASS GROUP DRUG;
  MODEL SCORE=GROUP DRUG GROUP*DRUG;
  MEANS GROUP DRUG GROUP*DRUG;
RUN; QUIT;
