/* CANDISC.SAS : ANALYSIS OF FISHER'S IRIS DATA */
OPTIONS PS=60 PAGENO=1;
PROC FORMAT;
  VALUE SPECNAME
     1='SETOSA    '
     2='VERSICOLOR'
     3='VIRGINICA ';
  VALUE SPECCHAR
     1='S'
     2='O'
     3='V';
RUN;
DATA IRIS;
  INFILE 'C:\Users\Admin\Desktop\°ø°³°­ÁÂ_14\dataset\Iris.DAT';
  INPUT X1-X4 SPECIES @@;
  FORMAT SPECIES SPECNAME.;
  LABEL X1='SEPAL LENGTH'
         X2='SEPAL WIDTH '
         X3='PETAL LENGTH'
         X4='PETAL WIDTH ';
PROC CANDISC DATA=IRIS OUT=CANOUT;
  CLASS SPECIES;
  VAR X1-X4;
RUN;
PROC PRINT DATA=CANOUT;
RUN;
PROC PLOT;
  PLOT CAN2*CAN1=SPECIES / VPOS=25;
  FORMAT SPECIES SPECCHAR.;
RUN;
PROC DISCRIM DATA=CANOUT LISTERR;
  CLASS SPECIES;
  VAR CAN1 CAN2;
RUN; QUIT;
