/* CATMOD2.SAS : LOGLINEAR MODEL */
DATA SURVIVAL2;
  INPUT HOSP $ SURV $ COND $ COUNT @@;
  DATALINES;
A D L 6  A S L 594  B D L 8 B S L 592
A D C 57 A S C 1443 B D C 8 B S C 192
;
RUN;
PROC CATMOD;
  WEIGHT COUNT;
  MODEL HOSP*SURV*COND=_RESPONSE_ / ML NOGLS PRED=FREQ;
  LOGLIN HOSP|SURV HOSP|COND SURV|COND;
RUN;
  LOGLIN HOSP|COND SURV|COND;
RUN;
QUIT;
