/*  CATMOD3.SAS : ANALYSIS USING LOGIT MODEL */
TITLE 'LOGIT MODEL OF MORTALITY DATA';
DATA MORT;
  INPUT S D T COUNT @@;
  DATALINES;
1 1 1 41 1 1 2 12 1 2 1 11 1 2 2  5
2 1 1 59 2 1 2 88 2 2 1 89 2 2 2 95
;
RUN;
PROC CATMOD;
  WEIGHT COUNT;
  POPULATION D T;
  MODEL S= D T / FREQ ML NOPROFILE;
RUN;
  MODEL S= D / FREQ ML NOPROFILE;
RUN;
  MODEL S= T / FREQ ML NOPROFILE;
RUN;
PROC CATMOD;
  WEIGHT COUNT;
  MODEL S*D*T=_RESPONSE_ / ML PRED=FREQ;
  LOGLIN S|D S|T D|T ;
RUN;
QUIT;
