/* CLUSTER2.SAS : ANALYSIS OF FIGHER'S IRIS DATA */
DATA IRIS;
  INFILE 'C:\Users\Admin\Desktop\°ø°³°­ÁÂ_14\dataset\Iris.DAT';
   INPUT X1-X4 SPEC_NO @@;
   IF SPEC_NO=1 THEN SPECIES='SETOSA    ';
   IF SPEC_NO=2 THEN SPECIES='VERSICOLOR';
   IF SPEC_NO=3 THEN SPECIES='VIRGINICA ';
   LABEL X1='SEPAL LENGTH'
         X2='SEPAL WIDTH '
         X3='PETAL LENGTH'
         X4='PETAL WIDTH ';
RUN;
PROC CLUSTER DATA=IRIS METHOD=WARD PRINT=15 CCC;
  VAR X1-X4;
  COPY SPECIES;
RUN;
PROC PLOT;
  PLOT _CCC_*_NCL_ / VPOS=25
    HAXIS=1 TO 25 BY 1;
RUN;
PROC TREE NOPRINT NCL=3 OUT=OUT;
  COPY X1-X4 SPECIES;
RUN;
PROC FREQ;
  TABLES CLUSTER*SPECIES;
RUN;
PROC CANDISC NOPRINT OUT=CAN;
  CLASS CLUSTER;
  VAR X1-X4;
RUN;
PROC PLOT;
  PLOT CAN2*CAN1=CLUSTER  / VPOS=25;
RUN; QUIT;
