/* CLUSTER4.SAS : 치수체계를 위한 군집분석 */
DATA PHYSICAL;
  INFILE 'C:\Users\Admin\Desktop\공개강좌_14\dataset\Physical.DAT'
              FIRSTOBS=2 MISSOVER;
  INPUT ID V1-V10;
  LABEL V1='신장' V2='총길이' V3='등길이' V4='화장' V5='소매길이'
        V6='바지길이' V7='밑위앞뒤' V8='가슴둘레' V9='허리둘레'
       V10='엉덩이둘레';
RUN;
PROC FASTCLUS DATA=PHYSICAL MAXCLUSTERS=10 OUT=OUTCLUS;
  VAR V1 V2 V5 V6 V8 V9 V10;
RUN;
PROC SORT DATA=OUTCLUS;
  BY CLUSTER;
RUN;
PROC MEANS DATA=OUTCLUS NOPRINT;
  VAR V1 V2 V5 V6 V8 V9 V10;
  BY CLUSTER;
  OUTPUT OUT=CLMEAN MEAN=MEANV1 MEANV2 MEANV5 MEANV6 MEANV8-MEANV10;
RUN;
PROC SORT DATA=CLMEAN OUT=CLMEAN;
  BY MEANV1;
RUN;
PROC PRINT DATA=CLMEAN;
  VAR MEANV1 MEANV2 MEANV5 MEANV6 MEANV8-MEANV10 _FREQ_;
RUN; QUIT;
