/* FREQ2.SAS : MARRIAGE SATISFACTION FREQUENCY TABLE */
DATA MARRIAGE;
  INPUT EDUC $ MSTATUS $ COUNT @@;
  DATALINES;
COLLEGE POOR 72  COLLEGE GOOD 112  COLLEGE EXCEL 245
HIGH    POOR 65  HIGH    GOOD  90  HIGH    EXCEL 120
MIDDLE  POOR 95  MIDDLE  GOOD 103  MIDDLE  EXCEL  98
;
RUN;
PROC FREQ ORDER=DATA;
  TABLES EDUC*MSTATUS /
      EXPECTED CHISQ NOCUM NOCOL NOROW NOPERCENT;
  WEIGHT COUNT;
RUN; QUIT;
