/* FREQ1.SAS : SURVIVAL RATE FREQUENCY TABLE */
DATA SURVIVAL;
  INPUT HOSP $ SURV $ COUNT @@;
  DATALINES;
A DEAD 63 A ALIVE 2037 B DEAD 16 B ALIVE 784
;
RUN;
PROC FREQ ORDER=DATA;
  TABLES HOSP SURV HOSP*SURV/
      EXPECTED CHISQ NOCUM NOCOL MEASURES;
  WEIGHT COUNT;
RUN; QUIT;
