/* G3D_SCATTER.SAS : G3D PROCEDURE */
GOPTIONS RESET;
TITLE1 'G3D SCATTER';
DATA CLASS;
  SET SASHELP.CLASS;
  LABEL HEIGHT="HEIGHT" 
  WEIGHT="WEIGHT" AGE="AGE";
  RUN;
PROC G3D DATA=CLASS;
  SCATTER HEIGHT*WEIGHT=AGE;
  RUN;
QUIT;