/* GDP.SAS : GPLOT PROCEDURE WITH OPTIONS */
DATA GDP;
  SET SASUSER.EXP_IMP;
RUN;
GOPTION RESET=SYMBOL;
GOPTION RESET=AXIS;
TITLE "Export, Import & GDP";
SYMBOL1 C=GREEN I=JOIN V=DOT H=0.2;
SYMBOL2 CI=RED CV=BLACK I=JOIN V=STAR H=0.5;
SYMBOL3 C=BLUE I=JOIN V=NONE;
AXIS1 C=GREEN MAJOR=(C=BLACK W=2 H=1) MINOR=(C=RED W=1 H=0.5 N=1)
      LABEL=(C=BLACK A=-90 R=90 "EXPORT & IMPORT") W=2;
AXIS2 C=BLUE MAJOR=(C=BLACK W=2 H=1) MINOR=(C=GREEN W=1 H=0.5 N=1)
      LABEL=(C=BLACK A=-90 R=90 "GDP") W=1;
AXIS3 C=BLACK;
LEGEND1 ACROSS=2 POSITION=(TOP LEFT INSIDE) VALUE=('EXPORT' 'IMPORT');
PROC GPLOT DATA=GDP;
  PLOT EXPORT*YEAR=1 IMPORT*YEAR=2 
       / OVERLAY VAXIS=AXIS1 HAXIS=AXIS3 LEGEND=LEGEND1;
  PLOT2 GDP*YEAR=3 / VAXIS=AXIS2 ;
RUN;
QUIT;
