/* GENMOD2.SAS : LOGLINEAR MODEL */
DATA SURVIVAL;
  INPUT HOSP $ SURV $ COND $ COUNT @@;
  DATALINES;
A D L 6  A S L 594  B D L 8 B S L 592
A D C 57 A S C 1443 B D C 8 B S C 192
;
RUN;
PROC GENMOD;
  CLASS HOSP SURV COND;
  MODEL COUNT=HOSP SURV COND HOSP*SURV HOSP*COND SURV*COND 
              / DIST=POI LINK=LOG ; RUN;
PROC GENMOD;
  CLASS HOSP SURV COND;
  MODEL COUNT=HOSP SURV COND HOSP*COND SURV*COND
              / DIST=POI LINK=LOG OBSTATS RESIDUALS;
RUN;  QUIT;


