/* GENMOD1.SAS : ANALYSIS OF SURVIVAL RATE FREQUENCY TABLE */
DATA SURVIVAL;
  INPUT HOSP $ SURV $ COUNT @@;
  DATALINES;
A DEAD 63 A ALIVE 2037 B DEAD 16 B ALIVE 784
;
RUN;
PROC GENMOD;
  CLASS HOSP SURV;
  MODEL COUNT=HOSP SURV HOSP*SURV / DIST=POI LINK=LOG;
RUN;
QUIT;
