/* MERGE3.SAS : MATCH-MERGE */
DATA PERSON;
  INPUT NAME $ RACE $ @@;
  CARDS;
MARY A MARY B MARY C ANN  F TOM  M
;
RUN;
DATA PLACE;
  INPUT NAME $ CITY $ REGION RACE $ @@;
  CARDS;
JOSE ERIE  5 R  MARY MIAMI 2 D  MARY BOSTON 4 B
MARY TAMPA 7 A  ANN  TAMPA 6 F
;
RUN;
PROC SORT DATA=PERSON;
  BY NAME RACE ;  RUN;
PROC SORT DATA=PLACE;
  BY NAME RACE;  RUN;
DATA RESULT;
  MERGE PERSON PLACE;
  BY NAME RACE;  RUN;
PROC PRINT DATA=RESULT;
RUN;
