/* MERGE1.SAS : ONE-TO-ONE MERGE */
DATA DRIVER;
  INPUT NAME $ CITY $ @@;
  CARDS;
CATHY PORTLAND  NANCY RALEIGH  SUE NASHIVILLE
;
RUN;
DATA VEHICLE;
  INPUT YEAR MODEL $ @@;
  CARDS;
1985 SEDAN 1952 JEEP 1978 BUS 1980 JEEP
;
RUN;
DATA MATCH;
  MERGE DRIVER(IN=INONE) VEHICLE(IN=INTWO);
  PUT NAME CITY YEAR MODEL INONE INTWO;
RUN;
PROC PRINT DATA=MATCH;
RUN; QUIT;