/* MERGE2.SAS : MATCH-MERGE */
DATA PERSON;
  INPUT NAME $ SEX $ @@;
  CARDS;
MARY F ANN  F TOM  M
;
RUN;
DATA PLACE;
  INPUT NAME $ CITY $ REGION @@;
  CARDS;
JOSE ERIE  5 MARY MIAMI 2
MARY TAMPA 7 ANN  TAMPA 6
;
RUN;
PROC SORT DATA=PERSON;
  BY NAME;  RUN;
PROC SORT DATA=PLACE;
  BY NAME;  RUN;
DATA RESULT;
  MERGE PERSON PLACE;
  BY NAME;  RUN;
PROC PRINT DATA=RESULT;
RUN; QUIT;