/* PIE.SAS : PIE CHART */
DATA HEART;
  SET SASUSER.HEART;
RUN;
GOPTION RESET=PATTERN;
GOPTION RESET=LEGEND;
PROC GCHART;
  PIE SHOCK / EXPLODE="CARDIO" SLICE=ARROW
              VALUE=NONE PERCENT=INSIDE;
  TITLE1 "Pie Chart";
RUN;
QUIT;
