/* REG1.SAS : ANALYSIS OF SIMPLE LIENAR REGRESSION */
DATA SIMPLE;
  INPUT DOSE HR @@;
     LDOSE=LOG10(DOSE);
  DATALINES;
2 60  2 58  4 63  4 62  8 67  8 65 16 70 16 70 32 74 32 73
;
RUN;
PROC PLOT DATA=SIMPLE;
  PLOT HR*DOSE='x' /vpos=20 ;
  PLOT HR*LDOSE='x'/vpos=20 ;
RUN;
PROC REG;
  MODEL HR=DOSE  ; OUTPUT OUT=NEW  P=PRED  R=RESID;
  MODEL HR=LDOSE ; OUTPUT OUT=NEW1 P=PRED1 R=RESID1;
RUN;
PROC PLOT DATA=NEW;
  PLOT HR*DOSE='x'  PRED*DOSE='p'   / OVERLAY vpos=20;
  PLOT RESID*DOSE='r' / VREF=0 vpos=20;
RUN;
PROC PLOT DATA=NEW1;
  PLOT HR*LDOSE='x' PRED1*LDOSE='p' / OVERLAY vpos=20;
  PLOT RESID1*LDOSE='r' / VREF=0 vpos=20;
RUN;
QUIT;

