/* STEPDISC.SAS : ANALYSIS OF FISHER'S IRIS DATA */
OPTIONS PS=60 PAGENO=1;
PROC FORMAT;
  VALUE SPECNAME
     1='SETOSA    '
     2='VERSICOLOR'
     3='VIRGINICA ';
  VALUE SPECCHAR
     1='S'
     2='O'
     3='V';
RUN;
DATA IRIS;
  INFILE 'C:\Users\Admin\Desktop\°ø°³°­ÁÂ_14\dataset\Iris.DAT';
  INPUT X1-X4 SPECIES @@;
  FORMAT SPECIES SPECNAME.;
  LABEL X1='SEPAL LENGTH'
         X2='SEPAL WIDTH '
         X3='PETAL LENGTH'
         X4='PETAL WIDTH ';
RUN;
PROC STEPDISC DATA=IRIS METHOD=STEPWISE;
  CLASS SPECIES;
  VAR X1-X4;
RUN;
PROC DISCRIM DATA=IRIS LISTERR;
  CLASS SPECIES;
  VAR X2 X3 X4;
RUN; QUIT;
