/* VBAR.SAS : VERTICAL BAR CHART */
DATA HEART;
  SET SASUSER.HEART;
RUN;
GOPTION RESET=PATTERN;
GOPTION RESET=LEGEND;
LEGEND1 ACROSS=3 POSITION=(BOTTOM CENTER OUTSIDE);
PROC GCHART;
  VBAR SURVIVE /GROUP=SEX SUBGROUP=SHOCK LEGEND=LEGEND1
                SPACE=3 RAXIS=0 TO 6 BY 1;
  TITLE1 "Vertical Bar Chart";
RUN;
QUIT;
